### PR TITLE
Change syntax from py2 to py3 using futurize

### PR DESCRIPTION
**Pull request by Khusbu**
## Context
We want to upgrade our repos to Py3. To start with, we would like to upgrade our [recruiterbox](https://github.com/Aplopio/recruiterbox) dependent libraries first. Most of them are official libraries and they have a version which is both Py2/3 compatible. However, there are some repos which are maintained by Aplopio .i.e. [google-api-python-client](https://github.com/Aplopio/google-api-python-client), [django_gapps_oauth2_login](https://github.com/Aplopio/django_gapps_oauth2_login) etc. These repos have been copy-pasted from their official repos (please note it was **not forked**) to cater to our project requirements. Hence, we have to make them Py2/3 compatible before we upgrade our Rbox repo. 

## Changes introduced 
In this PR, we will be upgrading `google-api-python-client`. I have used a python module [future](https://pypi.org/project/future/) which is the missing compatibility layer between Python 2 and Python 3. It allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead (as mentioned in their official PyPI page).

It makes changes to your code to support Py3 semantics but at the same time provide backward compatibility with Py2. These are based on lib2to3 and use fixers from 2to3, 3to2, and python-modernize. You can think of it as a wrapper with some added functionality. Some more information [here](http://python-future.org/automatic_conversion.html).

## How to test this??
I have updated our `recruiterbox`'s `requirements.txt` to use this branch of `google-api-python-client` instead of master. PR [here](https://github.com/Aplopio/recruiterbox/pull/24903) 
And YAYAYAYAY!!! all the python tests passed. 

But our python tests doesn't test for Py3 versions. [tox](https://pypi.org/project/tox/) is one way to do it. 

Also, I would like to test this on smoke machine before deploying it to production. Let me know if you have any suggestions. 

## Notes for reviewers
Let me know if you see any problem with `future` package. Will try to find an alternate module. 

## Jira ticket
https://atsico.atlassian.net/browse/RBE-841

### CODE REVIEW

**Comment by mri-dula** [comment]
I have a couple of questions:

1. Are all the code changes in the PR done by `futurize?`
2. So, we are going to test this with Python2 only right? Or with Python3 as well?

**Review by mri-dula — COMMENTED** [review]
I have a couple of questions:

1. Are all the code changes in the PR done by futurize?
2. So, we are going to test this with Python2 only right? Or with Python3 as well?

**Comment by sush-g** [comment]
I am assuming setting up CI env to support Python 3 would be part of this activity?

**Review by vedarthk — APPROVED** [review]
After these changes are merged, we need to bump the version and use that URL in the RB codebase

**Comment by Khusbu** [comment]
> I have a couple of questions:
> 
> 1. Are all the code changes in the PR done by futurize?
> 2. So, we are going to test this with Python2 only right? Or with Python3 as well?

1. Yes
2. For now only Py2. Later on we have to add tests for Py3 as well.

**Comment by Khusbu** [comment]
> I am assuming setting up CI env to support Python 3 would be part of this activity?

Yes we have a plan for it. But its not required for this PR. The changes are compatible with both Py2 and Py3.

**Pull request merged**
